### ISSUE TITLE
Why not put the while loop inside the main() function?

### ISSUE THREAD

**Issue by pkrog** [emelinepadie/python-ap#26]
https://github.com/emelinepadie/python-ap/blob/855748c8867e9f49aaf3c213ee8b58f31cb1e8fd/snake.py#L228C8-L229

**Comment by emelinepadie** [comment]
Bonjour,

J'ai effectué les modifications que vous m'avez suggérées.

Emeline Padié
________________________________
De : Pierrick Roger ***@***.***>
Envoyé : mercredi 13 décembre 2023 09:56
À : emelinepadie/python-ap ***@***.***>
Cc : Subscribed ***@***.***>
Objet : [emelinepadie/python-ap] Why not put the while loop inside the main() function? (Issue #26)


https://github.com/emelinepadie/python-ap/blob/855748c8867e9f49aaf3c213ee8b58f31cb1e8fd/snake.py#L228C8-L229
